from src.plots import plot_mesh_with_projections, get_2d_mask, draw_sphere, plot_mesh_mask
from src.algo import AlgorithmFactory, find_accessible_surface, find_accessible_surface_parallel, find_accessible_surface_open3d, find_accessible_surface_open3d_parallel, find_accessible_surface_trimesh, find_accessible_surface_trimesh_parallel
from src.utils import load_step, get_accessible_mesh, rotate_step_shape
from src.plots import get_step_units